### ISSUE TITLE
Articles haven't been being indexed by google after May 5

### ISSUE THREAD

**Issue by owendodd** [artsy/positron#1032]
Maybe related to AMP?

https://artsy.slack.com/archives/C083S2Y57/p1494255497895354

![image](https://cloud.githubusercontent.com/assets/3196536/25810621/f5fa9bb4-3410-11e7-95b7-60c23128c355.png)

**Comment by kanaabe** [comment]
@owendodd Can you check if this it still a problem? I'm looking at the same query and I'm seeing the Artsy link in results

**Comment by kanaabe** [comment]
All of the sudden we seem to be ranking great after I turned off Reflection crawling: 

["Dan Flavin"](https://www.google.com/search?q=ai+weiwei+nyc&tbm=nws&source=lnms&sa=X&ved=0ahUKEwjJ-taaoKzUAhUBPT4KHccRDTgQ_AUICigB&biw=1166&bih=1316&dpr=1#q=dan+flavin)
![image](https://user-images.githubusercontent.com/2236794/26892262-b31500b4-4b85-11e7-8291-835b5d6d7f2f.png)

["frieze new york best of"](https://www.google.com/search?q=the+very+best+of+frieze+new+york&oq=the+very+best+of+frieze+new+york&aqs=chrome..69i57j69i59j69i64l3.8451j0j7&sourceid=chrome&ie=UTF-8#q=frieze+new+york+best+of)
![image](https://user-images.githubusercontent.com/2236794/26892206-8c6976d4-4b85-11e7-80e1-bde25cfe83dd.png)

["puerto rico art fair"](https://www.google.com/search?q=puerto+rico+art+fair&oq=puerto+rico+art+fair&aqs=chrome..69i57j0.5399j0j9&sourceid=chrome&ie=UTF-8)
![image](https://user-images.githubusercontent.com/2236794/26892298-dcd4904a-4b85-11e7-990a-1e77309f8a95.png)

**Comment by kanaabe** [comment]
After digging with Christine we noticed that most articles are getting into Google News + indexed now. This is probably due to us turning Reflection off for articles. However we found a handful of outliers that still aren't getting into News. What's strange is that sometimes they get indexed but just don't get added to News. Other times they aren't indexed at all. On top of all this, none of the articles that had these problems had errors in Search Console. 😢  

Anyway we seem to be back to "normal" with the exception of a few articles. We should keep this open and I'll continue to monitor, but my feeling is that we've always had issues with some articles.
