### ISSUE TITLE
full list of drafts won't load in Writer

### ISSUE THREAD

**Issue by halleyjohnson** [artsy/positron#1152]
There are more drafts in the Editorial channel in Writer right now than will fit on one screen, but when I scroll down to load more, I get a spinner and no more articles. Have searched for missing ones to confirm the list is actually longer than what's showing up.
![screen shot 2017-06-30 at 10 51 51 am](https://user-images.githubusercontent.com/10982707/27741152-282d6f2c-5d82-11e7-8206-d227ac9765a5.png)
![screen shot 2017-06-30 at 10 51 58 am](https://user-images.githubusercontent.com/10982707/27741155-2a6f2230-5d82-11e7-945f-077adf95acae.png)

**Comment by eessex** [comment]
Looks like this is actually caused by a CORS error on the Unica font -- @kanaabe, is it correct that we should be able to proxy anything with an artsy.net domain on this?

**Comment by kanaabe** [comment]
Curious why that would be? I believe this bug has been around before the new font was added to Positron.

I do see a failing fetch for the stylesheet, but the Published list seems to be loading fine. It looks like the font fetch is failing because the CDN_URL is pointing to Positron's S3 bucket instead of Force's. We'll probably have to use a different name than CDN_URL to fetch the font for Positron. It's likely being overwritten atm in our Heroku configs which shouldn't change. Let's go through that tomorrow during pairing.

**Comment by eessex** [comment]
Sounds good -- if i turn on the cors chrome plugin the article list loads fine for me.
