### ISSUE TITLE
Related article callouts in Team Channels

### ISSUE THREAD

**Issue by eessex** [artsy/positron#1298]
We have now deprecated the callout entirely for new articles, but did team-channels were not considered in this decision. 

In new articles these references are moved to a sidebar, but where should we put them in a classic article?  

Perhaps it would make sense to talk to maintainers of the team-blogs and let them know this feature is being removed. 

Here's one example of a callout in use: http://localhost:5000/article/artsy-specialist-3-reasons-buy-art-fairs

**Comment by kanaabe** [comment]
Interesting. In Force, there's technically still support for them (since we split off from reaction and just render the classic component) so there isn't work to do there. So it's probably worth assessing how much time it would take to copy over the callout component from `edit/component/content` and support it in `content2`. It's probably also worth checking how many non-editorial articles have callouts. It feels like it wouldn't be too much work so I think supporting would be better than not if people really want them.

But if we don't want to support from a design POV then we should just axe it & notify. Soo I think this might be @owendodd's call!

**Comment by owendodd** [comment]
would it be possible to pull a list of non editorial articles using callouts? I tried to look at non-editorial impressions in looker, but came up empty handed. Makes me think that they may only be used by this new Buying with Artsy vertical, in which case I think its probably ok to just depreciate entirely

**Comment by kanaabe** [comment]
@owendodd yep! check out the `sections` field in looker and you can search by section type now. The type would be called `callout`

**Comment by owendodd** [comment]
Perfect, thanks!

Yeah so there are 9 records of callouts outside of editorial, and 5 of those are actually pull quotes. There is really just 1 use of it outside of this new 'Buying with Artsy' channel ([here](https://www.artsy.net/article/the-art-genome-project-seven-facts-about-the-art-genome-project)).

So based on all that, I think it makes sense to just depreciate the feature, people can still create plain text links if they need. I'll communicate that to the stakeholders who have used it. 

And then we just need to make sure the pull quote usages get transferred to our new way of handling them as part of the text sections.

**Comment by eessex** [comment]
Sounds good, will make sure we include all channels when converting pull quotes

**Comment by owendodd** [comment]
All stakeholders have been notified, callout death is imminent

**Comment by kanaabe** [comment]
Closing this in favor of https://github.com/artsy/positron/issues/1167 for actual callout deprecation, and https://github.com/artsy/publishing/issues/75 for supporting pullquotes in the classic layout.
