### ISSUE TITLE
Auto-save is running every few seconds regardless of activity

### ISSUE THREAD

**Issue by kanaabe** [artsy/positron#1360]
Getting a ton of autosaves without writing anything - has this come up for you @eessex ?

**Comment by eessex** [comment]
Draft registers a change on focus, so it does run when opening text containers.  However, I haven't seen it running erroneously outside of this.  Do you have more details on context?

**Comment by damassi** [comment]
@eessex - I think it's this bit [here](https://github.com/artsy/positron/blob/master/client/apps/edit/components/content2/index.coffee#L12). I really like how this works (for example, dropping a url in the video input field automatically saves, selecting a file automatically uploads), but I would make sure that you're not re-rendering the component tree unnecessarily. People often use [PureComponent](https://60devs.com/pure-component-in-react.html) around their app which will check to see if any props have changed and if not block render. It's useful, just make extra sure it's being used right otherwise things get weird!

**Comment by kanaabe** [comment]
Bumping this issue -- 

This causes a pretty bad experience for publishing drafts when someone else on the team has the draft open. If another draft is open, it polls the content of the open one which means hitting publish becomes useless (re-saves as a draft on the other session). In order to amend this (with rachel goss), we had to create a new article since we couldn't track down the open draft. 

We've previously had the autosave change only on key change. It seems like with the latest React work, the article is changing somewhere and triggering `saveArticle` when it doesn't need to. Handing this off to you, @eessex!

**Comment by damassi** [comment]
@eessex - when you find this can you ping me? Super curious; I dug and dug but couldn't track it down

**Comment by damassi** [comment]
@eessex / @kanaabe - can you paste the PR that this was fixed by? Curious to take a look at what the issue was.

**Comment by eessex** [comment]
Never actually found it -- replaced the saving with redux over repairing.

**Comment by damassi** [comment]
:mystery:

**Comment by kanaabe** [comment]
I'm pretty sure it had to do with our liberal usage of `forceUpdate`. Something was causing re-renders and the page always thought there was a change that needed to be resaved (triggered by that timeout checker). Something like that. 😅
