### ISSUE TITLE
How to develop as OS dev

### ISSUE THREAD

**Issue by meitros** [artsy/positron#1707]
Hi - I'm trying to figure out how to develop/write a diff on positron as an open source developer, and thought it would be prudent to open an issue. Here's what I've done so far:

1. Did a non-docker install on a linux box (with elasticsearch, mongodb)
2. used the oss credentials from artsy/force for the .env ARTSY_ID/ARTSY_SECRET
3. Deleted all "REPLACE" values from the config file (it was crashing with invalid values.) So far the code seems to skip things like sentry when the values are empty 
4. Created an account on staging.artsy.net.
5. Logged in. I get the following error:

```
https://stagingapi.artsy.net/oauth2/authorize?response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A3005%2Fauth%2Fartsy%2Fcallback&client_id=<SNIPPED>

The Eigen Open Source application is trying to redirect you to localhost. 
The redirect URL is not allowed by this application. Please choose "Back to Safety".
```

From this sequence I think my next question is what url should I use to allow for auth. But perhaps the answer is broader: there's a way to bypass auth while developing, or this repo is not a good candidate for oss development. Would definitely love to know your thoughts!

(p.s. I know metaphysics is open source, but is the api server? I didn't see it, but perhaps I could just look up the answer to my above question)

**Comment by kanaabe** [comment]
Hi @meitros! Thanks for opening this issue. It appears that the credentials for ARTSY_ID and ARTSY_SECRET from Force do not have access to Positron because of a missing redirect URL. I just enabled that now, but I would wait until tomorrow for it to land in staging. I would say this repo is a good candidate for OSS development!

Unfortunately Gravity (our main REST API server) is not open source. However, you should be able to work on Metaphysics without access to Gravity depending on the work you are trying to do. All you have to do is to point to staging urls. That info is available on the Metaphysics repo! Good luck.

**Comment by kanaabe** [comment]
Update for you @meitros, I added a few changes to our docs and our .env.example to better accommodate OSS devs like yourself so please take a look again and let me know if you have troubles. 

I checked the keys and they work fine now!
