### ISSUE TITLE
duplicate posts issue

### ISSUE THREAD

**Issue by halleyjohnson** [artsy/positron#236]
Finally got a test case for this! So the duplicate posts are here: https://www.artsy.net/post/editorial-liat-yossifors-eight-movements-applies-the-logic and here: https://www.artsy.net/post/editorial-liat-yossifors-eight-movements-applies-the-logic-1

What I did in Writer: 

+ made the post
+ synced to post
+ edited the post
+ synced to post, then saved article
+ edited the post
+ saved article, then synced to post

Then duplicate post appeared.

**Comment by craigspaeth** [comment]
Thanks for the repro! I think I'd rather just fix dupes manually until rollout rather than invest more time into sync-to-post issues. See my comments here for additional context https://github.com/artsy/positron/issues/240.

Your comments will still help give me context when debugging manually, so very much appreciated.
