### ISSUE TITLE
Slugs need to be more unique

### ISSUE THREAD

**Issue by craigspaeth** [artsy/positron#310]
Maybe use a date or ids in the url.

>  Articles with the same title by the same author are problematic. This is an issue with slugs not being unique... we can either A. Use ids + slugs e.g. /article//41ef1432f2/sabrina-buell-my-highlights-from-fog-design-plus-art-2015 like [Quartz does](http://qz.com/373228/hosting-the-winter-olympics-in-beijing-is-a-terrible-idea/) or B. Try to be a little more unique with the slug like adding last saved date/time to it e.g. /article/sabrina-buell-my-highlights-from-fog-design-plus-art-2015-03-30-2015

**Comment by halleyjohnson** [comment]
Maybe we can default to articles using IDs in the slugs rather than auto-grabbing the title? This would avoid having a bunch of slugs that pull "draft" for the slug, for example, and then the clean URL can be generated in posting, using that "generate using the author and title" function on the admin page? 

The issue for that would be dealing with this for partners somehow, and users who aren't admins.

**Comment by kanaabe** [comment]
Re-looking at this now. Have we decided to use dates in slugs going forward? If so, what format? 
/article/2015-09-23-artsy-editorial-armory-article-title
/article/artsy-editorial-armory-article-title-2015-09-23
I've seen the first one more IRL
