### ISSUE TITLE
articles published in 1970

### ISSUE THREAD

**Issue by halleyjohnson** [artsy/positron#333]
Still a handful of these. Not sure how to find them.

one here: https://www.artsy.net/article/artsy-editorial-at-the-guggenheim-a-march-through-on-kawara

another I've already fixed here: https://www.artsy.net/article/editorial-old-media-approached-anew-at-zane-bennett

**Comment by kanaabe** [comment]
There are approximately 47 articles that currently have the incorrect, 1970 `published_at` date. 
```
> db.articles.find( { "published_at": ISODate("1970-01-01T00:00:00.000Z") } ).count()
> 47
```
This might come from having an old article with a zero value date which converts to 1/1/1970 in UNIX format. Perhaps in migrating the articles the ISODate picked up this badly assigned date as well. 

I can provide links of the articles that have the incorrect date that should be changed. Otherwise, to really fix these articles, I'm thinking there needs to be an update to the database which takes the pre-Writer article's `published_at` date. I'm not sure what the old articles look like. This is just my hunch, do you have any ideas about this, @craigspaeth? 

@halleyjohnson Can you let me know if this is happening to newer articles, or just old ones?

**Comment by kanaabe** [comment]
Email sent with links
