### ISSUE TITLE
Super Article Partner Link

### ISSUE THREAD

**Issue by owendodd** [artsy/positron#596]
Super articles should have an optional partner link field, which would show up in the expanded header (https://github.com/artsy/force/issues/3818 )

![screen shot 2015-11-24 at 7 02 10 pm](https://cloud.githubusercontent.com/assets/3196536/11384539/9a288262-92de-11e5-9d6c-cbabed492d51.png)

**Comment by owendodd** [comment]
Partner Links would input in the admin panel:

<img width="862" alt="screen shot 2015-11-26 at 10 33 47 am" src="https://cloud.githubusercontent.com/assets/3196536/11426798/5ff0941e-942c-11e5-85dc-e253fe66f019.png">
<img width="863" alt="screen shot 2015-11-26 at 10 37 08 am" src="https://cloud.githubusercontent.com/assets/3196536/11426797/5fee7404-942c-11e5-8428-02994c0872cb.png">

**Comment by craigspaeth** [comment]
I think this also needs a "Partner Link Copy" field to fill in the "Download the Planet Art App" part.

**Comment by zamiang** [comment]
Couple additions to make it more reusable

- The + should be included in the Planet Art logo image (it is styled very specific to the style of the Planet Art logo)
- The secondary partner logo should have some text associated with it like "In partnership with" since that may not be something consistent across future logos in super posts.

![screenshot 2015-12-02 12 40 26](https://cloud.githubusercontent.com/assets/110563/11538886/104941f2-98f2-11e5-83f7-0d68ad26c889.png)
)

**Comment by owendodd** [comment]
Here is the admin implications of both of the above comments. Two new fields "Partner Link Title" and "Secondary Logo Text"


![screen shot 2015-12-02 at 2 36 11 pm](https://cloud.githubusercontent.com/assets/3196536/11541965/244ca138-9903-11e5-8b87-476145d7490b.png)
