### ISSUE TITLE
Smooth out load time on image resizer—Images appear at full size as page loads, then snap a few seconds later to the auto-resized width

### ISSUE THREAD

**Issue by halleyjohnson** [artsy/positron#724]
![screen shot 2016-04-21 at 17 11 52](https://cloud.githubusercontent.com/assets/10982707/14724438/2bb90aa6-07e4-11e6-88c6-af969f0ae65b.png)

![screen shot 2016-04-21 at 17 11 54](https://cloud.githubusercontent.com/assets/10982707/14724439/2e87e77a-07e4-11e6-857c-30d559309f70.png)

**Comment by owendodd** [comment]
I wonder if we could address this by adding some sort of image placeholder (something I would like to do anyways), that calculates based on VH. 

@kanaabe do you have any thoughts around easy fixes for this? I don't think we should invest much time into it (even though it is a bit annoying) because once we move to responsive we can kill this whole funky resize logic.

**Comment by kanaabe** [comment]
@owendodd @halleyjohnson i added a simple fade in to the images when they first load to prevent the jump -- let me know if that works!
